/**
 * FILE: User.scala
 * PACKAGE: com.poketracker.models
 * LOCATION: src/main/scala/com/poketracker/models/User.scala
 *
 * PURPOSE:
 *   Represents a registered user of PokéTracker.
 *
 * IMPORTS:
 *   zio.json.* — JsonCodec and DeriveJsonCodec for automatic JSON conversion
 *   java.time.Instant — JVM standard type for a point in time (UTC timestamp)
 *
 * USED BY: UserRepository, UserService, AuthRoutes
 */

package com.poketracker.models

import zio.json.*
import java.time.Instant

/**
 * ENUM: UserRole
 *
 * PURPOSE:
 *   Represents what type of user someone is.
 *   Using an enum instead of a raw String prevents typos and invalid values —
 *   the compiler rejects anything that is not one of these three values.
 *
 *   Collector — a regular user collecting and trading cards
 *   Vendor    — a shop or professional seller (opt-in, shows badge)
 *   Admin     — platform administrator with access to admin endpoints
 */
enum UserRole:
  case Collector, Vendor, Admin

object UserRole:
  given JsonCodec[UserRole] = JsonCodec.string.transform(
    s => UserRole.valueOf(s),
    r => r.toString
  )

/**
 * CASE CLASS: User
 *
 * PURPOSE:
 *   Represents a user account. Stored in the users table in PostgreSQL.
 *
 * @param id          UUID primary key. Generated by the database on insert.
 * @param username    Unique display name chosen by the user.
 * @param email       Email address. Used for notifications (future feature).
 * @param role        What type of user this is. Defaults to Collector.
 * @param reputation  Running reputation score from completed trades.
 *                    Starts at 0, increases with positive ratings.
 * @param location    City-level location for trade proximity matching.
 *                    e.g. "Austin, TX" — never an exact address.
 *                    Option because users can choose not to share location.
 * @param createdAt   When this account was created. Set by database on insert.
 */
final case class User(
  id:         String,
  username:   String,
  email:      String,
  role:       UserRole,
  reputation: Int,
  location:   Option[String],
  createdAt:  Instant
)

object User:
  given JsonCodec[User] = DeriveJsonCodec.gen[User]
