import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { HeaderNav } from '../components/HeaderNav'
import { useUser } from '../context/UserContext'
import { createBinder, listBinders } from '../api/binders'
import { getOwnedCards } from '../api/collection'
import { createDisplayCase, createSpace, createStorageUnit, listSpaces, placeBox, setDisplayLights } from '../api/rooms'
import { createBox, listBoxes } from '../api/storage'
import type { Binder, Card, CollectionSpace, StorageBox } from '../types'
import '../styles/spaces-concept.css'

type View='home'|'storage'|'binders'|'displays'

export function SpacesLivePage(){
  const {user}=useUser(),navigate=useNavigate()
  const [spaces,setSpaces]=useState<CollectionSpace[]>([]),[boxes,setBoxes]=useState<StorageBox[]>([]),[binders,setBinders]=useState<Binder[]>([]),[cards,setCards]=useState<Card[]>([])
  const [spaceId,setSpaceId]=useState(''),[view,setView]=useState<View>('home'),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const load=async()=>{if(!user?.id)return;setLoading(true);try{const [s,b,bi,o]=await Promise.all([listSpaces(user.id),listBoxes(user.id),listBinders(user.id),getOwnedCards(user.id)]);setSpaces(s);setBoxes(b);setBinders(bi);setCards(o.map(x=>x.card));setSpaceId(id=>id||s.find(x=>x.isDefault)?.id||s[0]?.id||'');setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load spaces')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[user?.id])
  const space=spaces.find(x=>x.id===spaceId)||spaces[0]
  const roomBoxes=useMemo(()=>boxes.filter(x=>!space||x.spaceId===space.id),[boxes,space])
  const roomBinders=useMemo(()=>binders.filter(x=>!space||x.spaceId===space.id),[binders,space])
  const addSpace=async()=>{if(!user?.id)return;const name=prompt('Space name')?.trim();if(!name)return;const made=await createSpace(user.id,name,'custom');setSpaces(x=>[...x,made]);setSpaceId(made.id)}
  if(loading)return <main className="page-tracker spaces-concept"><div className="spaces-live-status">Building your collection room…</div></main>
  return <main className="page-tracker spaces-concept"><div id="app" style={{display:'block'}}>
    <header className="spaces-site-header"><button className="logo spaces-home-button" onClick={()=>setView('home')}>MY <span>SPACES</span></button><div className="user-badge">● <b>{user?.username||'Collector'}</b></div><input className="header-search" placeholder="Search cards, binders, boxes, or locations…"/><HeaderNav/></header>
    {error&&<div className="spaces-live-error"><span>{error}</span><button onClick={load}>Retry</button></div>}
    {space&&view!=='home'&&<nav className="section-nav"><button onClick={()=>setView('home')}>‹ All spaces</button><div><button className={view==='storage'?'active':''} onClick={()=>setView('storage')}><i>▦</i><span><b>Storage</b><small>{roomBoxes.length} boxes</small></span></button><button className={view==='binders'?'active':''} onClick={()=>setView('binders')}><i>▥</i><span><b>Binder Library</b><small>{roomBinders.length} binders</small></span></button><button className={view==='displays'?'active':''} onClick={()=>setView('displays')}><i>◇</i><span><b>Display Gallery</b><small>{space.displayCases.length} cases</small></span></button></div></nav>}
    {!space?<div className="spaces-live-status"><h2>No spaces yet</h2><button onClick={addSpace}>Create a space</button></div>:view==='home'?<Home space={space} spaces={spaces} boxes={roomBoxes} binders={roomBinders} onView={setView} onSelect={setSpaceId} onAdd={addSpace}/>:view==='storage'?<Storage userId={user?.id||''} space={space} boxes={roomBoxes} reload={load}/>:view==='binders'?<Binders userId={user?.id||''} binders={roomBinders} reload={load} open={id=>navigate(`/spaces/${space.id}/binders/${id}`)}/>:<Displays userId={user?.id||''} space={space} cards={cards} reload={load}/>}
  </div></main>
}

function Home({space,spaces,boxes,binders,onView,onSelect,onAdd}:{space:CollectionSpace;spaces:CollectionSpace[];boxes:StorageBox[];binders:Binder[];onView:(v:View)=>void;onSelect:(id:string)=>void;onAdd:()=>void}){
  return <section className="spaces-home"><header><small>YOUR CARD-COLLECTING WORLD</small><h1>Every discovery has a place.</h1><p>Organize physical boxes, binders, variants, conditions, and display copies.</p><div className="atlas-elements"><span className="ember">△ Ember</span><span className="tide">≈ Tide</span><span className="grove">◇ Grove</span><span className="spark">ϟ Spark</span><span className="aether">✦ Aether</span></div></header><div className="main-space"><div className="space-art"><div className="space-architecture"><div className="art-storage"><i/><i/><i/><i/><i/><i/></div><div className="art-binders"><i/><i/><i/><i/><i/></div><div className="art-case"><span/><span/><span/><span/></div><div className="atlas-compass"><i/><b>✦</b></div></div></div><div className="space-info"><small>{space.isDefault?'PRIMARY COLLECTION SPACE':space.spaceType.replaceAll('_',' ').toUpperCase()}</small><h2>{space.name}</h2><p>One room with three distinct, live collection areas.</p><div className="space-destinations"><button onClick={()=>onView('storage')}><i>▦</i><span><b>Card Archive</b><small>{boxes.length} stackable boxes · {space.storageUnits.length} shelf units</small></span><strong>›</strong></button><button onClick={()=>onView('binders')}><i>▥</i><span><b>Field Guide Library</b><small>{binders.length} physical binders</small></span><strong>›</strong></button><button onClick={()=>onView('displays')}><i>✦</i><span><b>Discovery Gallery</b><small>{space.displayCases.length} illuminated cases</small></span><strong>›</strong></button></div></div></div><div className="other-spaces"><header><h3>Your other spaces</h3><button onClick={onAdd}>+ Add space</button></header><div>{spaces.filter(x=>x.id!==space.id).map((x,i)=><button key={x.id} onClick={()=>onSelect(x.id)}><i className={`other-icon icon-${i%3}`}/><span><b>{x.name}</b><small>{x.storageUnits.length} storage units · {x.displayCases.length} cases</small></span><strong>›</strong></button>)}</div></div></section>
}

function Storage({userId,space,boxes,reload}:{userId:string;space:CollectionSpace;boxes:StorageBox[];reload:()=>Promise<void>}){
  const [unitId,setUnitId]=useState(space.storageUnits[0]?.id||''),[drag,setDrag]=useState(''),[opening,setOpening]=useState('')
  const unit=space.storageUnits.find(x=>x.id===unitId)||space.storageUnits[0]
  const addUnit=async()=>{const name=prompt('Shelf name','Collector Rack')?.trim();if(!name)return;await createStorageUnit(userId,{spaceId:space.id,name,unitType:'rack',preset:'collector_rack',color:'#76533A',shelfCount:4,positionsPerShelf:5,maxStackHeight:3});await reload()}
  const addBox=async()=>{const name=prompt('Box name','New Card Box')?.trim();if(!name)return;await createBox(userId,name,'long-800',800,'#d8d0c0');await reload()}
  const drop=async(shelf:number,stack:number)=>{if(!unit||!drag)return;const current=boxes.filter(x=>x.storageUnitId===unit.id&&x.shelfIndex===shelf&&x.stackIndex===stack);if(current.length>=unit.maxStackHeight)return;await placeBox(userId,drag,{spaceId:space.id,unitId:unit.id,shelfIndex:shelf,stackIndex:stack,stackLevel:current.length});setDrag('');await reload()}
  return <section className="storage-view box-unit-view"><header className="gallery-heading"><div><small>{space.name.toUpperCase()} / STORAGE</small><h2>Card Archive</h2><p>{boxes.length} real boxes · drag and stack vertically</p></div><div><button onClick={addUnit}>+ Shelf unit</button><button className="primary" onClick={addBox}>+ Box</button></div></header><div className="live-unit-tabs">{space.storageUnits.map(x=><button className={unit?.id===x.id?'active':''} onClick={()=>setUnitId(x.id)} key={x.id}>{x.name}<small>{boxes.filter(b=>b.storageUnitId===x.id).length} boxes</small></button>)}</div>{!unit?<div className="spaces-live-status"><h2>No furniture yet</h2><button onClick={addUnit}>Add collector rack</button></div>:<div className="physical-shelving">{Array.from({length:unit.shelfCount},(_,shelf)=><section className="physical-shelf" key={shelf}><header><span>SHELF {String.fromCharCode(65+shelf)}</span><b>{unit.positionsPerShelf} POSITIONS · STACK {unit.maxStackHeight} HIGH</b></header><div className="physical-shelf-bay">{Array.from({length:unit.positionsPerShelf},(_,stack)=>{const pile=boxes.filter(x=>x.storageUnitId===unit.id&&x.shelfIndex===shelf&&x.stackIndex===stack).sort((a,b)=>(a.stackLevel||0)-(b.stackLevel||0));return <div className={`stack-position ${drag?'drop-ready':''}`} onDragOver={e=>e.preventDefault()} onDrop={()=>void drop(shelf,stack)} key={stack}>{pile.map(box=><button key={box.id} draggable onDragStart={()=>setDrag(box.id)} onDragEnd={()=>setDrag('')} onClick={()=>{setOpening(box.id);setTimeout(()=>setOpening(''),650)}} className={`physical-box box-model-${box.boxType||'custom'} ${opening===box.id?'is-open opening-to-inventory':''}`} style={{'--chosen-box-color':box.color||'#d8d0c0'} as React.CSSProperties}><span className="box-lid"/><span className="box-handles"><i/><i/></span><span className="box-label"><strong>{box.name}</strong><small>{box.drawers.reduce((n,d)=>n+d.cardCount,0)} / {box.capacity||'custom'} cards</small></span><span className="box-open-hint">{opening===box.id?'OPENING…':`LEVEL ${(box.stackLevel||0)+1} · DRAG`}</span></button>)}<button className="stack-drop" disabled={pile.length>=unit.maxStackHeight}>{pile.length?'DROP ON TOP':'+ DROP BOX'}</button></div>})}</div><footer><i/><span>BOXES FACE FORWARD AND EXTEND INTO THE SHELF</span><i/></footer></section>)}</div>}<aside className="unplaced-boxes"><b>UNPLACED BOXES</b>{boxes.filter(x=>!x.storageUnitId).map(box=><button draggable onDragStart={()=>setDrag(box.id)} onDragEnd={()=>setDrag('')} key={box.id}><i style={{background:box.color}}/><span>{box.name}<small>{box.boxType} · drag onto a shelf</small></span></button>)}</aside></section>
}

function Binders({userId,binders,reload,open}:{userId:string;binders:Binder[];reload:()=>Promise<void>;open:(id:string)=>void}){
  const add=async()=>{const name=prompt('Binder name','New Collection Binder')?.trim();if(!name)return;await createBinder(userId,name,'Nine');await reload()}
  return <section className="binder-view"><header className="gallery-heading"><div><small>COLLECTION ROOM / BINDERS</small><h2>Field Guide Library</h2><p>{binders.length} physical binders</p></div><button className="primary" onClick={add}>+ Add binder</button></header><div className="binder-room"><div className="binder-shelf-title"><small>COLLECTION SHELF</small><b>YOUR BINDERS</b></div><div className="binder-bookcase">{binders.map((b,i)=><button key={b.id} onClick={()=>open(b.id)} style={{'--binder':['#8b443b','#315c75','#66507b','#b18642','#4e684b'][i%5]} as React.CSSProperties}><i className="binder-ring"/><span>{b.name}</span><small>{b.pocketSize.toUpperCase()} POCKET</small><em/></button>)}{!binders.length&&<div className="binder-empty"><b>No binders here yet</b><span>Add your first binder.</span></div>}</div><div className="binder-plank"/></div></section>
}

function Displays({userId,space,cards,reload}:{userId:string;space:CollectionSpace;cards:Card[];reload:()=>Promise<void>}){
  const display=space.displayCases[0],shown=cards.slice(0,4)
  const add=async()=>{await createDisplayCase(userId,{spaceId:space.id,name:'Illuminated Collection',caseType:'lit_cabinet',preset:'collector_led',frameColor:'#17141F',lightColor:'#FFF1B8',shelfCount:3,slotsPerShelf:4});await reload()}
  const toggle=async()=>{if(display){await setDisplayLights(userId,display.id,!display.lightEnabled);await reload()}}
  return <section className={`display-gallery ${display?.lightEnabled?'lights-on':'lights-off'}`}><header className="gallery-heading"><div><small>{space.name.toUpperCase()} / DISPLAYS</small><h2>{display?.name||'Discovery Gallery'}</h2><p>{display?`${display.shelfCount} shelves · ${display.slots.length} persisted slots`:'No display case yet'}</p></div><div>{display&&<button onClick={toggle}>{display.lightEnabled?'☀ Lights on':'☾ Lights off'}</button>}<button className="primary" onClick={add}>+ Display case</button></div></header>{display?<div className="gallery-stage"><div className="gallery-wall"><div className="gallery-title"><small>{display.caseType.replaceAll('_',' ').toUpperCase()}</small><b>{display.name}</b><i/></div></div><div className="gallery-floor"/><section className="museum-cabinet"><div className="cabinet-crown"><span><small>CURATED COLLECTION</small><b>{display.name}</b></span><i className="cabinet-lock">◆</i></div><div className="led top-led"/><div className="cabinet-interior"><i className="back-panel"/><i className="door left-door"/><i className="door right-door"/><i className="center-seam"/><div className="display-row row-one">{shown.slice(0,2).map(c=><button key={c.id}><i className="spotlight"/><img src={c.images.small} alt={c.name}/><em className="card-stand"/><span><b>{c.name}</b><small>{c.rarity||'Owned card'}</small></span></button>)}</div><i className="glass-shelf shelf-one"/><div className="display-row row-two">{shown.slice(2).map(c=><button key={c.id}><i className="spotlight"/><img src={c.images.small} alt={c.name}/><em className="card-stand"/><span><b>{c.name}</b><small>{c.rarity||'Owned card'}</small></span></button>)}</div><i className="glass-shelf shelf-two"/><i className="glass-reflection"/></div><footer><span><i className="green"/> Settings saved</span><span>{display.slots.length} slots</span><span>LED display</span></footer><div className="cabinet-base"><i/><i/><i/></div></section></div>:<div className="spaces-live-status"><h2>Build your first real display case</h2><button onClick={add}>Add illuminated cabinet</button></div>}</section>
}
